// Generated by `wit-bindgen` 0.46.0. DO NOT EDIT!
// Options used:
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum SerializationFormat {
    Json,
    MessagePack,
}
impl ::core::fmt::Debug for SerializationFormat {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            SerializationFormat::Json => {
                f.debug_tuple("SerializationFormat::Json").finish()
            }
            SerializationFormat::MessagePack => {
                f.debug_tuple("SerializationFormat::MessagePack").finish()
            }
        }
    }
}
impl SerializationFormat {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> SerializationFormat {
        if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
        }
        match val {
            0 => SerializationFormat::Json,
            1 => SerializationFormat::MessagePack,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
pub type Buffer = _rt::Vec<u8>;
#[derive(Clone)]
pub enum BotError {
    Deserialize(_rt::String),
    Serialize(_rt::String),
    Processing(_rt::String),
    BotCore(Buffer),
}
impl ::core::fmt::Debug for BotError {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            BotError::Deserialize(e) => {
                f.debug_tuple("BotError::Deserialize").field(e).finish()
            }
            BotError::Serialize(e) => {
                f.debug_tuple("BotError::Serialize").field(e).finish()
            }
            BotError::Processing(e) => {
                f.debug_tuple("BotError::Processing").field(e).finish()
            }
            BotError::BotCore(e) => f.debug_tuple("BotError::BotCore").field(e).finish(),
        }
    }
}
impl ::core::fmt::Display for BotError {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        write!(f, "{:?}", self)
    }
}
impl std::error::Error for BotError {}
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_default_settings_cabi<T: Guest>(arg0: i32) -> *mut u8 {
    unsafe {
        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
        let result0 = { T::default_settings(SerializationFormat::_lift(arg0 as u8)) };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result0 {
            Ok(e) => {
                *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                let vec2 = (e).into_boxed_slice();
                let ptr2 = vec2.as_ptr().cast::<u8>();
                let len2 = vec2.len();
                ::core::mem::forget(vec2);
                *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr2
                    .cast_mut();
            }
            Err(e) => {
                *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                match e {
                    BotError::Deserialize(e) => {
                        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                            as u8;
                        let vec3 = (e.into_bytes()).into_boxed_slice();
                        let ptr3 = vec3.as_ptr().cast::<u8>();
                        let len3 = vec3.len();
                        ::core::mem::forget(vec3);
                        *ptr1
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr3.cast_mut();
                    }
                    BotError::Serialize(e) => {
                        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                            as u8;
                        let vec4 = (e.into_bytes()).into_boxed_slice();
                        let ptr4 = vec4.as_ptr().cast::<u8>();
                        let len4 = vec4.len();
                        ::core::mem::forget(vec4);
                        *ptr1
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len4;
                        *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr4.cast_mut();
                    }
                    BotError::Processing(e) => {
                        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32)
                            as u8;
                        let vec5 = (e.into_bytes()).into_boxed_slice();
                        let ptr5 = vec5.as_ptr().cast::<u8>();
                        let len5 = vec5.len();
                        ::core::mem::forget(vec5);
                        *ptr1
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr5.cast_mut();
                    }
                    BotError::BotCore(e) => {
                        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32)
                            as u8;
                        let vec6 = (e).into_boxed_slice();
                        let ptr6 = vec6.as_ptr().cast::<u8>();
                        let len6 = vec6.len();
                        ::core::mem::forget(vec6);
                        *ptr1
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len6;
                        *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr6.cast_mut();
                    }
                }
            }
        };
        ptr1
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_default_settings<T: Guest>(arg0: *mut u8) {
    unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
            0 => {
                let l1 = *arg0
                    .add(::core::mem::size_of::<*const u8>())
                    .cast::<*mut u8>();
                let l2 = *arg0
                    .add(2 * ::core::mem::size_of::<*const u8>())
                    .cast::<usize>();
                let base3 = l1;
                let len3 = l2;
                _rt::cabi_dealloc(base3, len3 * 1, 1);
            }
            _ => {
                let l4 = i32::from(
                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                );
                match l4 {
                    0 => {
                        let l5 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l6 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l5, l6, 1);
                    }
                    1 => {
                        let l7 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l8 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l7, l8, 1);
                    }
                    2 => {
                        let l9 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l10 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l9, l10, 1);
                    }
                    _ => {
                        let l11 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l12 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base13 = l11;
                        let len13 = l12;
                        _rt::cabi_dealloc(base13, len13 * 1, 1);
                    }
                }
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_validate_settings_cabi<T: Guest>(
    arg0: i32,
    arg1: *mut u8,
    arg2: usize,
) -> *mut u8 {
    unsafe {
        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
        let result1 = {
            let len0 = arg2;
            T::validate_settings(
                SerializationFormat::_lift(arg0 as u8),
                _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
            )
        };
        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result1 {
            Ok(e) => {
                *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                match e {
                    Some(e) => {
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                            as u8;
                        let vec3 = (e).into_boxed_slice();
                        let ptr3 = vec3.as_ptr().cast::<u8>();
                        let len3 = vec3.len();
                        ::core::mem::forget(vec3);
                        *ptr2
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr2
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr3.cast_mut();
                    }
                    None => {
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                            as u8;
                    }
                };
            }
            Err(e) => {
                *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                match e {
                    BotError::Deserialize(e) => {
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                            as u8;
                        let vec4 = (e.into_bytes()).into_boxed_slice();
                        let ptr4 = vec4.as_ptr().cast::<u8>();
                        let len4 = vec4.len();
                        ::core::mem::forget(vec4);
                        *ptr2
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len4;
                        *ptr2
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr4.cast_mut();
                    }
                    BotError::Serialize(e) => {
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                            as u8;
                        let vec5 = (e.into_bytes()).into_boxed_slice();
                        let ptr5 = vec5.as_ptr().cast::<u8>();
                        let len5 = vec5.len();
                        ::core::mem::forget(vec5);
                        *ptr2
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr2
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr5.cast_mut();
                    }
                    BotError::Processing(e) => {
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32)
                            as u8;
                        let vec6 = (e.into_bytes()).into_boxed_slice();
                        let ptr6 = vec6.as_ptr().cast::<u8>();
                        let len6 = vec6.len();
                        ::core::mem::forget(vec6);
                        *ptr2
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len6;
                        *ptr2
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr6.cast_mut();
                    }
                    BotError::BotCore(e) => {
                        *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32)
                            as u8;
                        let vec7 = (e).into_boxed_slice();
                        let ptr7 = vec7.as_ptr().cast::<u8>();
                        let len7 = vec7.len();
                        ::core::mem::forget(vec7);
                        *ptr2
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len7;
                        *ptr2
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr7.cast_mut();
                    }
                }
            }
        };
        ptr2
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_validate_settings<T: Guest>(arg0: *mut u8) {
    unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
            0 => {
                let l1 = i32::from(
                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                );
                match l1 {
                    0 => {}
                    _ => {
                        let l2 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l3 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l2;
                        let len4 = l3;
                        _rt::cabi_dealloc(base4, len4 * 1, 1);
                    }
                }
            }
            _ => {
                let l5 = i32::from(
                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                );
                match l5 {
                    0 => {
                        let l6 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l7 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l6, l7, 1);
                    }
                    1 => {
                        let l8 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l9 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l8, l9, 1);
                    }
                    2 => {
                        let l10 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l11 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l10, l11, 1);
                    }
                    _ => {
                        let l12 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l13 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base14 = l12;
                        let len14 = l13;
                        _rt::cabi_dealloc(base14, len14 * 1, 1);
                    }
                }
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_settings_schema_cabi<T: Guest>() -> *mut u8 {
    unsafe {
        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
        let result0 = { T::settings_schema() };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        let vec2 = (result0.into_bytes()).into_boxed_slice();
        let ptr2 = vec2.as_ptr().cast::<u8>();
        let len2 = vec2.len();
        ::core::mem::forget(vec2);
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
        *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
        ptr1
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_settings_schema<T: Guest>(arg0: *mut u8) {
    unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
    }
}
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_decide_cabi<T: Guest>(
    arg0: i32,
    arg1: *mut u8,
    arg2: usize,
    arg3: *mut u8,
    arg4: usize,
) -> *mut u8 {
    unsafe {
        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
        let result2 = {
            let len0 = arg2;
            let len1 = arg4;
            T::decide(
                SerializationFormat::_lift(arg0 as u8),
                _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                _rt::Vec::from_raw_parts(arg3.cast(), len1, len1),
            )
        };
        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result2 {
            Ok(e) => {
                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                match e {
                    Some(e) => {
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                            as u8;
                        let vec4 = (e).into_boxed_slice();
                        let ptr4 = vec4.as_ptr().cast::<u8>();
                        let len4 = vec4.len();
                        ::core::mem::forget(vec4);
                        *ptr3
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len4;
                        *ptr3
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr4.cast_mut();
                    }
                    None => {
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                            as u8;
                    }
                };
            }
            Err(e) => {
                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                match e {
                    BotError::Deserialize(e) => {
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                            as u8;
                        let vec5 = (e.into_bytes()).into_boxed_slice();
                        let ptr5 = vec5.as_ptr().cast::<u8>();
                        let len5 = vec5.len();
                        ::core::mem::forget(vec5);
                        *ptr3
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr3
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr5.cast_mut();
                    }
                    BotError::Serialize(e) => {
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                            as u8;
                        let vec6 = (e.into_bytes()).into_boxed_slice();
                        let ptr6 = vec6.as_ptr().cast::<u8>();
                        let len6 = vec6.len();
                        ::core::mem::forget(vec6);
                        *ptr3
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len6;
                        *ptr3
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr6.cast_mut();
                    }
                    BotError::Processing(e) => {
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32)
                            as u8;
                        let vec7 = (e.into_bytes()).into_boxed_slice();
                        let ptr7 = vec7.as_ptr().cast::<u8>();
                        let len7 = vec7.len();
                        ::core::mem::forget(vec7);
                        *ptr3
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len7;
                        *ptr3
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr7.cast_mut();
                    }
                    BotError::BotCore(e) => {
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32)
                            as u8;
                        let vec8 = (e).into_boxed_slice();
                        let ptr8 = vec8.as_ptr().cast::<u8>();
                        let len8 = vec8.len();
                        ::core::mem::forget(vec8);
                        *ptr3
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len8;
                        *ptr3
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr8.cast_mut();
                    }
                }
            }
        };
        ptr3
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_decide<T: Guest>(arg0: *mut u8) {
    unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
            0 => {
                let l1 = i32::from(
                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                );
                match l1 {
                    0 => {}
                    _ => {
                        let l2 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l3 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l2;
                        let len4 = l3;
                        _rt::cabi_dealloc(base4, len4 * 1, 1);
                    }
                }
            }
            _ => {
                let l5 = i32::from(
                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                );
                match l5 {
                    0 => {
                        let l6 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l7 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l6, l7, 1);
                    }
                    1 => {
                        let l8 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l9 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l8, l9, 1);
                    }
                    2 => {
                        let l10 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l11 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l10, l11, 1);
                    }
                    _ => {
                        let l12 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l13 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base14 = l12;
                        let len14 = l13;
                        _rt::cabi_dealloc(base14, len14 * 1, 1);
                    }
                }
            }
        }
    }
}
pub trait Guest {
    #[allow(async_fn_in_trait)]
    fn default_settings(format: SerializationFormat) -> Result<Buffer, BotError>;
    #[allow(async_fn_in_trait)]
    fn validate_settings(
        format: SerializationFormat,
        settings: Buffer,
    ) -> Result<Option<Buffer>, BotError>;
    #[allow(async_fn_in_trait)]
    fn settings_schema() -> _rt::String;
    #[allow(async_fn_in_trait)]
    fn decide(
        format: SerializationFormat,
        settings: Buffer,
        player_state: Buffer,
    ) -> Result<Option<Buffer>, BotError>;
}
#[doc(hidden)]
#[macro_export]
macro_rules! __export_world_game_bot_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "default-settings")] unsafe extern "C"
        fn export_default_settings(arg0 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_default_settings_cabi::<$ty > (arg0) } } #[unsafe
        (export_name = "cabi_post_default-settings")] unsafe extern "C" fn
        _post_return_default_settings(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_default_settings::<$ty > (arg0) } } #[unsafe (export_name =
        "validate-settings")] unsafe extern "C" fn export_validate_settings(arg0 : i32,
        arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_validate_settings_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
        (export_name = "cabi_post_validate-settings")] unsafe extern "C" fn
        _post_return_validate_settings(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_validate_settings::<$ty > (arg0) } } #[unsafe (export_name =
        "settings-schema")] unsafe extern "C" fn export_settings_schema() -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_settings_schema_cabi::<$ty > () } }
        #[unsafe (export_name = "cabi_post_settings-schema")] unsafe extern "C" fn
        _post_return_settings_schema(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_settings_schema::<$ty > (arg0) } } #[unsafe (export_name =
        "decide")] unsafe extern "C" fn export_decide(arg0 : i32, arg1 : * mut u8, arg2 :
        usize, arg3 : * mut u8, arg4 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_decide_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4) }
        } #[unsafe (export_name = "cabi_post_decide")] unsafe extern "C" fn
        _post_return_decide(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_decide::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_game_bot_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_game_bot_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_game_bot_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_game_bot_impl as export;
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.46.0:example:game-interface:game-bot:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 470] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd7\x02\x01A\x02\x01\
A\x11\x01m\x02\x04json\x0cmessage-pack\x03\0\x14serialization-format\x03\0\0\x01\
p}\x03\0\x06buffer\x03\0\x02\x01q\x04\x0bdeserialize\x01s\0\x09serialize\x01s\0\x0a\
processing\x01s\0\x08bot-core\x01\x03\0\x03\0\x09bot-error\x03\0\x04\x01j\x01\x03\
\x01\x05\x01@\x01\x06format\x01\0\x06\x04\0\x10default-settings\x01\x07\x01k\x03\
\x01j\x01\x08\x01\x05\x01@\x02\x06format\x01\x08settings\x03\0\x09\x04\0\x11vali\
date-settings\x01\x0a\x01@\0\0s\x04\0\x0fsettings-schema\x01\x0b\x01@\x03\x06for\
mat\x01\x08settings\x03\x0cplayer-state\x03\0\x09\x04\0\x06decide\x01\x0c\x04\0\x1f\
example:game-interface/game-bot\x04\0\x0b\x0e\x01\0\x08game-bot\x03\0\0\0G\x09pr\
oducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.239.0\x10wit-bindgen-rust\x06\
0.46.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
