// Autogenerated from Rust shared-types (ts-rs).
// Regenerate using:
// cargo run -p upjs-gdd-shared-types --features typegen --bin export_ts

export type PublishToken = {
  token: string;
  user_id: string;
  expires_at: number;
};

export type ValidationDiagnostic = {
  severity: string;
  code: string;
  message: string;
};

export type ValidationReport = {
  ok: boolean;
  errors: number;
  warnings: number;
  infos: number;
  diagnostics: ValidationDiagnostic[];
};

export type DraftLite = {
  id: string;
  game_name: string;
  version: string;
  status: string;
};

export type UploadGameZipResponse = {
  upload_id: string;
  draft?: DraftLite | null;
  report: ValidationReport;
};

export type GameManifest = {
  name: string;
  display_name: string;
  version: string;
  description: string;
};

export type RealtimeEnvelope = {
  channel: string;
  event: string;
  payload: unknown;
};
