// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum SerializationFormat {
    Json,
    MessagePack,
}
impl ::core::fmt::Debug for SerializationFormat {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            SerializationFormat::Json => {
                f.debug_tuple("SerializationFormat::Json").finish()
            }
            SerializationFormat::MessagePack => {
                f.debug_tuple("SerializationFormat::MessagePack").finish()
            }
        }
    }
}
impl SerializationFormat {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> SerializationFormat {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => SerializationFormat::Json,
            1 => SerializationFormat::MessagePack,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
pub type Buffer = _rt::Vec<u8>;
#[derive(Clone)]
pub enum GameCoreError {
    Deserialize(_rt::String),
    Serialize(_rt::String),
    Processing(_rt::String),
    GameCore(Buffer),
}
impl ::core::fmt::Debug for GameCoreError {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            GameCoreError::Deserialize(e) => {
                f.debug_tuple("GameCoreError::Deserialize").field(e).finish()
            }
            GameCoreError::Serialize(e) => {
                f.debug_tuple("GameCoreError::Serialize").field(e).finish()
            }
            GameCoreError::Processing(e) => {
                f.debug_tuple("GameCoreError::Processing").field(e).finish()
            }
            GameCoreError::GameCore(e) => {
                f.debug_tuple("GameCoreError::GameCore").field(e).finish()
            }
        }
    }
}
impl ::core::fmt::Display for GameCoreError {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        write!(f, "{:?}", self)
    }
}
impl std::error::Error for GameCoreError {}
pub type Player = Buffer;
pub type PlayerAction = (Player, Buffer);
#[derive(Clone)]
pub struct PlayerState {
    pub player: Player,
    pub state: Buffer,
}
impl ::core::fmt::Debug for PlayerState {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PlayerState")
            .field("player", &self.player)
            .field("state", &self.state)
            .finish()
    }
}
#[derive(Clone)]
pub struct NewPlayerState {
    pub state: PlayerState,
    pub events: _rt::Vec<Buffer>,
}
impl ::core::fmt::Debug for NewPlayerState {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("NewPlayerState")
            .field("state", &self.state)
            .field("events", &self.events)
            .finish()
    }
}
#[derive(Clone)]
pub struct Game {
    pub full_state: Buffer,
    pub player_states: _rt::Vec<PlayerState>,
}
impl ::core::fmt::Debug for Game {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Game")
            .field("full-state", &self.full_state)
            .field("player-states", &self.player_states)
            .finish()
    }
}
#[derive(Clone)]
pub struct TakeActionResult {
    pub new_game_full_state: Buffer,
    pub player_states: _rt::Vec<NewPlayerState>,
}
impl ::core::fmt::Debug for TakeActionResult {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("TakeActionResult")
            .field("new-game-full-state", &self.new_game_full_state)
            .field("player-states", &self.player_states)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_init_cabi<T: Guest>(
    arg0: i32,
    arg1: *mut u8,
    arg2: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg2;
    let result1 = T::init(
        SerializationFormat::_lift(arg0 as u8),
        _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
    );
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Ok(e) => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            let Game { full_state: full_state3, player_states: player_states3 } = e;
            let vec4 = (full_state3).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
            let vec8 = player_states3;
            let len8 = vec8.len();
            let layout8 = _rt::alloc::Layout::from_size_align_unchecked(
                vec8.len() * (4 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result8 = if layout8.size() != 0 {
                let ptr = _rt::alloc::alloc(layout8).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout8);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec8.into_iter().enumerate() {
                let base = result8.add(i * (4 * ::core::mem::size_of::<*const u8>()));
                {
                    let PlayerState { player: player5, state: state5 } = e;
                    let vec6 = (player5).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = (state5).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                }
            }
            *ptr2.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result8;
        }
        Err(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            match e {
                GameCoreError::Deserialize(e) => {
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                    let vec9 = (e.into_bytes()).into_boxed_slice();
                    let ptr9 = vec9.as_ptr().cast::<u8>();
                    let len9 = vec9.len();
                    ::core::mem::forget(vec9);
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
                    *ptr2
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr9.cast_mut();
                }
                GameCoreError::Serialize(e) => {
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                    let vec10 = (e.into_bytes()).into_boxed_slice();
                    let ptr10 = vec10.as_ptr().cast::<u8>();
                    let len10 = vec10.len();
                    ::core::mem::forget(vec10);
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
                    *ptr2
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr10.cast_mut();
                }
                GameCoreError::Processing(e) => {
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32)
                        as u8;
                    let vec11 = (e.into_bytes()).into_boxed_slice();
                    let ptr11 = vec11.as_ptr().cast::<u8>();
                    let len11 = vec11.len();
                    ::core::mem::forget(vec11);
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
                    *ptr2
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr11.cast_mut();
                }
                GameCoreError::GameCore(e) => {
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32)
                        as u8;
                    let vec12 = (e).into_boxed_slice();
                    let ptr12 = vec12.as_ptr().cast::<u8>();
                    let len12 = vec12.len();
                    ::core::mem::forget(vec12);
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
                    *ptr2
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr12.cast_mut();
                }
            }
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base3 = l1;
            let len3 = l2;
            _rt::cabi_dealloc(base3, len3 * 1, 1);
            let l4 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l5 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base12 = l4;
            let len12 = l5;
            for i in 0..len12 {
                let base = base12.add(i * (4 * ::core::mem::size_of::<*const u8>()));
                {
                    let l6 = *base.add(0).cast::<*mut u8>();
                    let l7 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base8 = l6;
                    let len8 = l7;
                    _rt::cabi_dealloc(base8, len8 * 1, 1);
                    let l9 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l10 = *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base11 = l9;
                    let len11 = l10;
                    _rt::cabi_dealloc(base11, len11 * 1, 1);
                }
            }
            _rt::cabi_dealloc(
                base12,
                len12 * (4 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
        }
        _ => {
            let l13 = i32::from(
                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l13 {
                0 => {
                    let l14 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l15 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l14, l15, 1);
                }
                1 => {
                    let l16 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l17 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l16, l17, 1);
                }
                2 => {
                    let l18 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l19 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l18, l19, 1);
                }
                _ => {
                    let l20 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l21 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base22 = l20;
                    let len22 = l21;
                    _rt::cabi_dealloc(base22, len22 * 1, 1);
                }
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_take_action_cabi<T: Guest>(
    arg0: i32,
    arg1: *mut u8,
    arg2: usize,
    arg3: *mut u8,
    arg4: usize,
    arg5: *mut u8,
    arg6: usize,
    arg7: *mut u8,
    arg8: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg2;
    let base7 = arg3;
    let len7 = arg4;
    let mut result7 = _rt::Vec::with_capacity(len7);
    for i in 0..len7 {
        let base = base7.add(i * (4 * ::core::mem::size_of::<*const u8>()));
        let e7 = {
            let l1 = *base.add(0).cast::<*mut u8>();
            let l2 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len3 = l2;
            let l4 = *base
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l5 = *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len6 = l5;
            PlayerState {
                player: _rt::Vec::from_raw_parts(l1.cast(), len3, len3),
                state: _rt::Vec::from_raw_parts(l4.cast(), len6, len6),
            }
        };
        result7.push(e7);
    }
    _rt::cabi_dealloc(
        base7,
        len7 * (4 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let len8 = arg6;
    let len9 = arg8;
    let result10 = T::take_action(
        SerializationFormat::_lift(arg0 as u8),
        Game {
            full_state: _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
            player_states: result7,
        },
        (
            _rt::Vec::from_raw_parts(arg5.cast(), len8, len8),
            _rt::Vec::from_raw_parts(arg7.cast(), len9, len9),
        ),
    );
    let ptr11 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result10 {
        Ok(e) => {
            *ptr11.add(0).cast::<u8>() = (0i32) as u8;
            let TakeActionResult {
                new_game_full_state: new_game_full_state12,
                player_states: player_states12,
            } = e;
            let vec13 = (new_game_full_state12).into_boxed_slice();
            let ptr13 = vec13.as_ptr().cast::<u8>();
            let len13 = vec13.len();
            ::core::mem::forget(vec13);
            *ptr11.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
            *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr13
                .cast_mut();
            let vec20 = player_states12;
            let len20 = vec20.len();
            let layout20 = _rt::alloc::Layout::from_size_align_unchecked(
                vec20.len() * (6 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
            let result20 = if layout20.size() != 0 {
                let ptr = _rt::alloc::alloc(layout20).cast::<u8>();
                if ptr.is_null() {
                    _rt::alloc::handle_alloc_error(layout20);
                }
                ptr
            } else {
                ::core::ptr::null_mut()
            };
            for (i, e) in vec20.into_iter().enumerate() {
                let base = result20.add(i * (6 * ::core::mem::size_of::<*const u8>()));
                {
                    let NewPlayerState { state: state14, events: events14 } = e;
                    let PlayerState { player: player15, state: state15 } = state14;
                    let vec16 = (player15).into_boxed_slice();
                    let ptr16 = vec16.as_ptr().cast::<u8>();
                    let len16 = vec16.len();
                    ::core::mem::forget(vec16);
                    *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len16;
                    *base.add(0).cast::<*mut u8>() = ptr16.cast_mut();
                    let vec17 = (state15).into_boxed_slice();
                    let ptr17 = vec17.as_ptr().cast::<u8>();
                    let len17 = vec17.len();
                    ::core::mem::forget(vec17);
                    *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len17;
                    *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr17.cast_mut();
                    let vec19 = events14;
                    let len19 = vec19.len();
                    let layout19 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec19.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result19 = if layout19.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout19).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout19);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec19.into_iter().enumerate() {
                        let base = result19
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec18 = (e).into_boxed_slice();
                            let ptr18 = vec18.as_ptr().cast::<u8>();
                            let len18 = vec18.len();
                            ::core::mem::forget(vec18);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len18;
                            *base.add(0).cast::<*mut u8>() = ptr18.cast_mut();
                        }
                    }
                    *base.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len19;
                    *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result19;
                }
            }
            *ptr11.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len20;
            *ptr11.add(3 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result20;
        }
        Err(e) => {
            *ptr11.add(0).cast::<u8>() = (1i32) as u8;
            match e {
                GameCoreError::Deserialize(e) => {
                    *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                    let vec21 = (e.into_bytes()).into_boxed_slice();
                    let ptr21 = vec21.as_ptr().cast::<u8>();
                    let len21 = vec21.len();
                    ::core::mem::forget(vec21);
                    *ptr11
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len21;
                    *ptr11
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr21.cast_mut();
                }
                GameCoreError::Serialize(e) => {
                    *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                    let vec22 = (e.into_bytes()).into_boxed_slice();
                    let ptr22 = vec22.as_ptr().cast::<u8>();
                    let len22 = vec22.len();
                    ::core::mem::forget(vec22);
                    *ptr11
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len22;
                    *ptr11
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr22.cast_mut();
                }
                GameCoreError::Processing(e) => {
                    *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32)
                        as u8;
                    let vec23 = (e.into_bytes()).into_boxed_slice();
                    let ptr23 = vec23.as_ptr().cast::<u8>();
                    let len23 = vec23.len();
                    ::core::mem::forget(vec23);
                    *ptr11
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len23;
                    *ptr11
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr23.cast_mut();
                }
                GameCoreError::GameCore(e) => {
                    *ptr11.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32)
                        as u8;
                    let vec24 = (e).into_boxed_slice();
                    let ptr24 = vec24.as_ptr().cast::<u8>();
                    let len24 = vec24.len();
                    ::core::mem::forget(vec24);
                    *ptr11
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len24;
                    *ptr11
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr24.cast_mut();
                }
            }
        }
    };
    ptr11
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_take_action<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base3 = l1;
            let len3 = l2;
            _rt::cabi_dealloc(base3, len3 * 1, 1);
            let l4 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l5 = *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base18 = l4;
            let len18 = l5;
            for i in 0..len18 {
                let base = base18.add(i * (6 * ::core::mem::size_of::<*const u8>()));
                {
                    let l6 = *base.add(0).cast::<*mut u8>();
                    let l7 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base8 = l6;
                    let len8 = l7;
                    _rt::cabi_dealloc(base8, len8 * 1, 1);
                    let l9 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l10 = *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base11 = l9;
                    let len11 = l10;
                    _rt::cabi_dealloc(base11, len11 * 1, 1);
                    let l12 = *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l13 = *base
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base17 = l12;
                    let len17 = l13;
                    for i in 0..len17 {
                        let base = base17
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l14 = *base.add(0).cast::<*mut u8>();
                            let l15 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base16 = l14;
                            let len16 = l15;
                            _rt::cabi_dealloc(base16, len16 * 1, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base17,
                        len17 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
            }
            _rt::cabi_dealloc(
                base18,
                len18 * (6 * ::core::mem::size_of::<*const u8>()),
                ::core::mem::size_of::<*const u8>(),
            );
        }
        _ => {
            let l19 = i32::from(
                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l19 {
                0 => {
                    let l20 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l21 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l20, l21, 1);
                }
                1 => {
                    let l22 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l23 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l22, l23, 1);
                }
                2 => {
                    let l24 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l25 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l24, l25, 1);
                }
                _ => {
                    let l26 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l27 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base28 = l26;
                    let len28 = l27;
                    _rt::cabi_dealloc(base28, len28 * 1, 1);
                }
            }
        }
    }
}
pub trait Guest {
    fn init(format: SerializationFormat, config: Buffer) -> Result<Game, GameCoreError>;
    fn take_action(
        format: SerializationFormat,
        game: Game,
        player_action: PlayerAction,
    ) -> Result<TakeActionResult, GameCoreError>;
}
#[doc(hidden)]
macro_rules! __export_world_game_core_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "init")] unsafe extern "C" fn
        export_init(arg0 : i32, arg1 : * mut u8, arg2 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_init_cabi::<$ty > (arg0, arg1, arg2) } } #[unsafe
        (export_name = "cabi_post_init")] unsafe extern "C" fn _post_return_init(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
        #[unsafe (export_name = "take-action")] unsafe extern "C" fn
        export_take_action(arg0 : i32, arg1 : * mut u8, arg2 : usize, arg3 : * mut u8,
        arg4 : usize, arg5 : * mut u8, arg6 : usize, arg7 : * mut u8, arg8 : usize,) -> *
        mut u8 { unsafe { $($path_to_types)*:: _export_take_action_cabi::<$ty > (arg0,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
        "cabi_post_take-action")] unsafe extern "C" fn _post_return_take_action(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_take_action::<$ty > (arg0)
        } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_game_core_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_game_core_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_game_core_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_game_core_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:example:game-interface:game-core:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 628] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf4\x03\x01A\x02\x01\
A\x1a\x01m\x02\x04json\x0cmessage-pack\x03\0\x14serialization-format\x03\0\0\x01\
p}\x03\0\x06buffer\x03\0\x02\x01q\x04\x0bdeserialize\x01s\0\x09serialize\x01s\0\x0a\
processing\x01s\0\x09game-core\x01\x03\0\x03\0\x0fgame-core-error\x03\0\x04\x03\0\
\x06player\x03\0\x03\x01o\x02\x06\x03\x03\0\x0dplayer-action\x03\0\x07\x01r\x02\x06\
player\x06\x05state\x03\x03\0\x0cplayer-state\x03\0\x09\x01p\x03\x01r\x02\x05sta\
te\x0a\x06events\x0b\x03\0\x10new-player-state\x03\0\x0c\x01p\x0a\x01r\x02\x0afu\
ll-state\x03\x0dplayer-states\x0e\x03\0\x04game\x03\0\x0f\x01p\x0d\x01r\x02\x13n\
ew-game-full-state\x03\x0dplayer-states\x11\x03\0\x12take-action-result\x03\0\x12\
\x01j\x01\x10\x01\x05\x01@\x02\x06format\x01\x06config\x03\0\x14\x04\0\x04init\x01\
\x15\x01j\x01\x13\x01\x05\x01@\x03\x06format\x01\x04game\x10\x0dplayer-action\x08\
\0\x16\x04\0\x0btake-action\x01\x17\x04\0\x20example:game-interface/game-core\x04\
\0\x0b\x0f\x01\0\x09game-core\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
